name: ⚙️ CI

on:
  # Trigger automatically on pushes and pull requests to main
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allow manual runs from the Actions tab in GitHub
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # --- Step 1: Check out the repository code ---
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Step 2: Set up the Go environment ---
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      # --- Step 3: Create the output directory ---
      - name: Create output directory
        run: mkdir -p output

      # --- Step 4: Compile all examples and check for failures ---
      # This step iterates through all example files and runs the compiler.
      # GitHub Actions runs this script with a setting that causes it to
      # fail immediately if any command exits with a non-zero status.
      - name: Compile all examples and check exit codes
        run: |
          for file in docs/examples/example*_input.mecha; do
            echo "--- 🚀 Compiling $file ---"
          
            # Define a unique output file name based on the input
            output_file="output/$(basename "$file" _input.mecha)_workflow_output.txt"
          
            # Run the compiler
            go run ./cmd/mecha/main.go -i "$file" -o "$output_file"
          done
          
          echo "--- ✅ All examples compiled successfully ---"